on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: update release  Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_KEY }}
          script: |
            ls -a
            cd minibazar
            git pull origin main
            mix deps.get
            MIX_ENV=prod mix compile
            MIX_ENV=prod mix ecto.migrate
            npm run deploy --prefix ./assets
            mix phx.digest
            POOL_SIZE=4 MIX_ENV=prod mix release --overwrite

            _build/prod/rel/mini_bazar/bin/mini_bazar stop
            _build/prod/rel/mini_bazar/bin/mini_bazar daemon

          