on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-elixir@1.11.4
        with:
          otp-version: ${{matrix.otp}} 
          elixir-version: ${{matrix.elixir}}

      - name: update release  Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_KEY }}
          script: |
            sh build_release_deploy.sh
          